### PR TITLE
Update README.md before archiving?

### PR DESCRIPTION
**Pull request by maelle**
See also new repo DESCRIPTION

### CODE REVIEW

**Comment by cboettig** [comment]
@sckott @maelle Do we have any confirmation that Mendeley is actually working on a replacement?  (That would be great; and we should probably archive either way)

**Comment by maelle** [comment]
No I don't I jist read that in the readme, maybe best to delete?

**Comment by cboettig** [comment]
Then I'm guessing they aren't planning on that, in which case, @noamross has made a good case that maybe we should revisit our maintenance of this package.  It would probably be relatively quick to do a straight-forward port of their python sdk into R with the modern R toolkit (this version is still using RCurl & ROAuth!)

**Comment by maelle** [comment]
Aha so no archiving? Maybe add a WIP or concept badge then?

**Comment by cboettig** [comment]
:+1: A concept badge sounds appropriate

**Comment by maelle** [comment]
Ok done! `rodev::use_repostatus_badge` is very useful today hehe. https://github.com/ropenscilabs/rodev

**Comment by cboettig** [comment]
okay, not enough coffee this morning, I somehow thought Mendeley was figshare.  I think we should archive RMendeley

**Pull request closed without merging**
